### ISSUE TITLE
ID可以给弄短一些吗

### ISSUE THREAD

**Issue by MilesPan** [WindrunnerMax/FileTransfer#4]
俩电脑在局域网内似乎也搜索不到，只能手动输id，但是发现id真的好长

**Comment by WindRunnerMax** [comment]
手动输入确实有点麻烦，但是本意这个id是用来在公网之间互联的，在有ipv6的情况下是可以直接互联的

我觉得可能是得研究一下为什么局域网之间相互发现不了，是跨路由器了吗还是AP隔离了

**Comment by WindRunnerMax** [comment]
或者你也可以在局域网内直接部署一份，应该就没什么问题了

**Comment by MilesPan** [comment]
解决了，把梯子给关了就能搜到手机了...

**Comment by WindRunnerMax** [comment]
确实，如果走代理的话，你的ip是代理的ip地址，那肯定就相互发现不到了
